name: Release

on: 
  push:
    branches: [ release ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: Remove SNAPSHOT
        run: mvn org.codehaus.mojo:versions-maven-plugin:2.8.1:set -DremoveSnapshot=true
      
      - name: Get Version
        id: get_version
        run: |
          echo ::set-output name=pversion::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
         
      - name: Get Previous Tag Name
        id: get_previous_tag_name
        run: |
          echo ::set-output name=ptag::$(git describe --abbrev=0 --tags)
      
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      
      - name: Make Extra Folder
        run: mkdir ./mswing-demo/target/mswing-demo-lib/mswing-demo-lib
      
      - name: Move Dependencies to Created Folder
        run: mv ./mswing-demo/target/mswing-demo-lib/*.jar ./mswing-demo/target/mswing-demo-lib/mswing-demo-lib/
      
      - name: Archive Demo for Release
        uses: papeloto/action-zip@v1
        with:
          files: ./mswing-demo/target/mswing-demo-lib/ ./mswing-demo/target/mswing-demo-${{ steps.get_version.outputs.pversion }}.jar
          dest: ./mswing-demo/target/mswing-demo-${{ steps.get_version.outputs.pversion }}.zip
      
      - name: Archive Comps for Release
        uses: papeloto/action-zip@v1
        with:
          files: ./mswing-comps/target/mswing-comps-${{ steps.get_version.outputs.pversion }}.jar
          dest: ./mswing-comps/target/mswing-comps-${{ steps.get_version.outputs.pversion }}.zip
      
      - name: Create Changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: ${{ secrets.MYGITHUB_TOKEN }}
          sinceTag: ${{ steps.get_previous_tag_name.outputs.ptag }}
          excludeLabels: 'development' 
          output: temp_changelog.md
          unreleased: true
          issues: true
          issuesWoLabels: true
          pullRequests: true
          prWoLabels: true
          filterByMilestone: false
          stripGeneratorNotice: true
          stripHeaders: true
        
      - run: |
          tee < ./temp_changelog.md
        
      - name: Read changelog
        id: read-changelog
        uses: juliangruber/read-file-action@v1
        with:
          path: ./temp_changelog.md
    
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.pversion }}
          release_name: mswing-v${{ steps.get_version.outputs.pversion }}
          draft: false
          prerelease: false
          body: |
            ## Changes in v${{ steps.get_version.outputs.pversion }}
            ${{ steps.read-changelog.outputs.content }}
            
      - name: Attach Demo Artifact to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./mswing-demo/target/mswing-demo-${{ steps.get_version.outputs.pversion }}.zip
          asset_name: mswing-demo-${{ steps.get_version.outputs.pversion }}.zip
          asset_content_type: application/zip
      
      - name: Attach Lib Artifact to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./mswing-comps/target/mswing-comps-${{ steps.get_version.outputs.pversion }}.zip
          asset_name: mswing-comps-${{ steps.get_version.outputs.pversion }}.zip
          asset_content_type: application/zip
      
      - run: |
          echo "## Changes in mswing-v${{ steps.get_version.outputs.pversion }}" >> CHANGELOG.md
          echo "${{ steps.read-changelog.outputs.content }}" >> CHANGELOG.md
      
      - name: Fetch Next Development Version in POM File
        run: mvn org.codehaus.mojo:versions-maven-plugin:2.8.1:set -DnextSnapshot=true
      
      - run: git config user.name "GitHub Actions" && git config user.email "actions@github.com"
      - run: git status
      - run: git add pom.xml mswing-demo/pom.xml mswing-comps/pom.xml CHANGELOG.md
      - run: git commit -m "Updated pom.xml files and CHANGELOG.md for new version"
      - run: git fetch origin release
      - run: git push origin HEAD:release
      - run: git fetch origin master
      - run: git push origin HEAD:master
